services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  suricata:
    image: jasonish/suricata:latest
    command: -c /etc/suricata/suricata.yaml -r /pcaps/attack.pcap
    volumes:
      - ./configs/suricata.yaml:/etc/suricata/suricata.yaml
      - ./configs/local.rules:/etc/suricata/rules/local.rules:ro
      - ../data/pcaps:/pcaps
      - ./logs/suricata:/var/log/suricata

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    user: root
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/suricata:/var/log/suricata:ro
    depends_on:
      - elasticsearch
    command: [ "--strict.perms=false" ]

  elastalert:
    image: jertel/elastalert2:2.19.0
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ../detection/elastalert/config.yaml:/opt/elastalert/config.yaml
      - ../detection/elastalert/rules:/opt/elastalert/rules
    depends_on:
      - elasticsearch

volumes:
  es-data:
